### ISSUE TITLE
Goofed on the Equipment Durability INI's

### ISSUE THREAD

**Issue by ShadesofDawn** [SovnSkyrim/AmongSovngardesStars#10]
So made a slight error on ED's INI files when I reduced the chance for tempered gear on normal enemies down to 1%.   It's been causing issues with stacking since then it seems.   I've corrected the ini's and here they are for future inclusion in 0.5.4.  It won't let me add INI files so here is the raw data.   First is the No HUD version

[Degradation]
DisableDegradation=true
OnlyPlayer=false
NoBreakMagicDisallowEnchanting=true
IncreaseDurability=true
EquipmentHealthThreshold=0

[DegradationRate]
WeaponSword=0.0
WeaponDagger=0.0
WeaponWarAxe=0.0
WeaponMace=0.0
WeaponGreatSword=0.0
WeaponHammer=0.0
WeaponBattleAxe=0.0
WeaponBow=0.0
WeaponCrossbow=0.0
LightArmor=0.0
HeavyArmor=0.0
Clothing=0.0
DefaultArmor=0.0
PowerAttackMultiplier=2.0
FollowerMultiplier=1.0
NPCMultiplier=1.0

[BreakChance]
WeaponSword=0.0
WeaponDagger=0.0
WeaponWarAxe=0.0
WeaponMace=0.0
WeaponGreatSword=0.0
WeaponHammer=0.0
WeaponBattleAxe=0.0
WeaponBow=0.0
WeaponCrossbow=0.0
LightArmor=0.0
HeavyArmor=0.0
Clothing=0.0
DefaultArmor=0.0
PowerAttackMultiplier=2.0
FollowerMultiplier=1.0
NPCMultiplier=1.0

[DynamicTemper]
DisableDynamicTemper=false
TemperChance=00
BossTemperChance=80

[Widget]
DisableWidget=false
; Set PositionX and PositionY to values between 0 and 100
PositionX=3
PositionY=73
Scale=100
UnbreakableColor=0xFFFFFF
BreakableColor=0xFFD700
HidePoisonName=false
HideWithWeaponsSheathed=true
ToggleKeyCode=0
; Choose from the following and add numbers.
; For example, if you set to 12, weapon and armor names are not displayed.
; 1 - Reverse
; 2 - Hide Shout
; 4 - Hide Weapon Name
; 8 - Hide Armor Name
; 16 - Hide Equipment Health
Flags=30

===================================================================================
HUD Enabled Version
===================================================================================
[Degradation]
DisableDegradation=true
OnlyPlayer=false
NoBreakMagicDisallowEnchanting=true
IncreaseDurability=true
EquipmentHealthThreshold=0

[DegradationRate]
WeaponSword=0.0
WeaponDagger=0.0
WeaponWarAxe=0.0
WeaponMace=0.0
WeaponGreatSword=0.0
WeaponHammer=0.0
WeaponBattleAxe=0.0
WeaponBow=0.0
WeaponCrossbow=0.0
LightArmor=0.0
HeavyArmor=0.0
Clothing=0.0
DefaultArmor=0.0
PowerAttackMultiplier=2.0
FollowerMultiplier=1.0
NPCMultiplier=1.0

[BreakChance]
WeaponSword=0.0
WeaponDagger=0.0
WeaponWarAxe=0.0
WeaponMace=0.0
WeaponGreatSword=0.0
WeaponHammer=0.0
WeaponBattleAxe=0.0
WeaponBow=0.0
WeaponCrossbow=0.0
LightArmor=0.0
HeavyArmor=0.0
Clothing=0.0
DefaultArmor=0.0
PowerAttackMultiplier=2.0
FollowerMultiplier=1.0
NPCMultiplier=1.0

[DynamicTemper]
DisableDynamicTemper=false
TemperChance=00
BossTemperChance=80

[Widget]
DisableWidget=false
; Set PositionX and PositionY to values between 0 and 100
PositionX=3
PositionY=73
Scale=100
UnbreakableColor=0xFFFFFF
BreakableColor=0xFFD700
HidePoisonName=false
HideWithWeaponsSheathed=true
ToggleKeyCode=0
; Choose from the following and add numbers.
; For example, if you set to 12, weapon and armor names are not displayed.
; 1 - Reverse
; 2 - Hide Shout
; 4 - Hide Weapon Name
; 8 - Hide Armor Name
; 16 - Hide Equipment Health
Flags=8

**Comment by Althro** [comment]
Thanks for this, I've updated them now.
