### ISSUE TITLE
Suggestion: Swap Frostfall to Frostbite

### ISSUE THREAD

**Issue by kociara81** [SovnSkyrim/AmongSovngardesStars#2]
I know that Frostfall is a core part of Lexy's guide and many people like it's rigorous cold weather recognition, but it's also really script heavy for the game (and glitchy sometimes). 

A few months ago, the mod with a more lightweight approach to cold weather recognition got released and It's called Frostbite. It's not only a lightweight approach but also it was created to be as much compatible with as many mods out of the box as possible. 

But it had its cost and cons. Frostbite to calculate how cold is, it's only using time of the day and weather outside, to do it. So it isn't so precise unlike Frostfall, but still, it's doing its job.

I'm thinking it's worth to try it and give it a chance.

Link:  https://www.nexusmods.com/skyrimspecialedition/mods/27693

**Comment by SovnSkyrim** [comment]
No
