### ISSUE TITLE
Merge-Revisted Series still broke

### ISSUE THREAD

**Issue by ShadesofDawn** [SovnSkyrim/AmongSovngardesStars#9]
Lighting is corrected but Bleak Falls Barrow at the very least is still loading the vanilla cell's floor plan in some places resulting in an non-completable dungeon.   Holes in the floor, switches that are missing, doorways that are behind walls where there should be a new archway, etc.   Below is a screen shot showing what I'm talking about and is only one of several errors in BFB.
![enb2020_10_30_20_57_59](https://user-images.githubusercontent.com/73726257/97767685-11ecb500-1af4-11eb-8d12-f9d5518506da.jpg)

**Comment by Althro** [comment]
Can you give me the rough location of it so I can check it?

**Comment by ShadesofDawn** [comment]
Head through Bleak Falls Barrow until you get to the first swinging pendulum blades trap.   Just past this, as you follow the path to the left, you will see a door on your right.   Go through the door and take the stairs down.   Take the first left and it should lead you to this door.   If you go back to where you went through the door and continue on the vanilla path, you will notice a down gate, the switch is missing and there is a passage behind a vanilla wall in that section.   The vanilla wall should be gone and replaced by an open archway.

**Comment by Althro** [comment]
Disciple might have fixed this, will need to check.

**Comment by Althro** [comment]
Fixed by reworking the merge.
